# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Stylish Reader Extension CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install web-ext
      run: pnpm install web-ext -g
    - run: pnpm install
      working-directory: ./src
    - run: pnpm release 
      working-directory: ./src
    - name: Package
      run: web-ext build
      working-directory: ./src
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4.3.6
      with:
          name: dist-without-markdown
          path: |
            ./src/web-ext-artifacts/
      
